### PR TITLE
Feature/md to rst

### PR DESCRIPTION
**Pull request by jonas-eschle**
Use rst instead of md

---
This change is [Reviewable](https://reviewable.io/reviews/phynix/uniphy/29)

### CODE REVIEW

**Comment by SebastianJL** [comment]
Why the format change?

**Comment by jonas-eschle** [comment]
Ah sorry, forgot to mention: PyPI want's rst, not md (AFAIK).

**Comment by SebastianJL** [comment]
Can you push the branch, so I can see on github if the rst is displayed correctly?

**Comment by jonas-eschle** [comment]
Hm, I think the branch is pushed already, isn't it? But here you should find it: https://github.com/Phynix/uniphy/tree/feature/md_to_rst

Does it work?
And yes, rst works with github as well.

**Review by SebastianJL — APPROVED** [review]

**Pull request merged**
