### PR TITLE
Create issue_template.md

### PR DESCRIPTION
**Pull request by SebastianJL**
It might be usefull to create this issue template to streamline the way issues are written.
I included:
 - User stories
 - Bug reports

Any other idea?

---
This change is [Reviewable](https://reviewable.io/reviews/phynix/uniphy/21)

### CODE REVIEW

**Comment by SebastianJL** [comment]
@mayou36  Can you get codeclimate to ignore this issue?

**Comment by SebastianJL** [comment]
Ok did the igoring in #23

**Comment by jonas-eschle** [comment]
Yes, I can have em explicitly ignoring the issue, done that.

**Comment by jonas-eschle** [comment]
@SebastianJL anything else? otherwise I think this can be merged.

Btw did you add the typot or did it do that by itself/have I once allowed it to do that? Is it annoying?

**Review by jonas-eschle — APPROVED** [review]

**Comment by SebastianJL** [comment]
No i didn't add typot.

**Pull request merged**
